### ISSUE TITLE
Automatically check for outdated rules

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#1008]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I was taking a look at [OpenFisca France](https://github.com/openfisca/openfisca-france) and I wanted to know which rules (to be more specific: variables' formulas and parameters) required an update. Some updates are impossible to foresee, but others are known beforehand because the law establishes when values and behaviours will be subject to change.

### Here is what I expected to happen:

To be able to do something like:

```
$ openfisca rules:outdated
...
./some/path/parameter.yaml:L123 is outdated.
./some/path/variable.py:L123 is outdated.
./other/path/variable.py:L123 is due soon.
```

### Here is what actually happened:

Nothing of the sort.

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.
- Lobbyist _(I model reforms to make them exist)_.

**Comment by MattiSG** [comment]
Thanks @maukoquiroga, this was indeed considered at some point when establishing the new parameters format in #523 🙂

However, one has to keep in mind that legislation expected updates are often late to come (at least in France), and that often an expected update actually yields the same value than the previous one.
Moreover, the contributors who use (and thus feel responsible) for maintaining some parameters or variables have their own way to track changes (and usually do so in advance of the expected date, or know when it is actually going to change).
On the other hand, I don't see maintainers who do not have knowledge of the specific policy area would go looking for updates just because some contributor marked it as “expected” at some point in time.
Finally, it is worth keeping in mind that any subset of any country package model is likely to be outdated at some point in time; but that our collective experience is that it is better to have a stable, functional model rather than a “more accurate” model that no one is actually in charge of. I am not certain it is the responsibility of Core to suggest ways to keep track of outdated legislation, at least not without a very clear understanding of how individual teams do so today.

I am thus not certain the complexity-to-benefit balance is positive on that feature —or at least I was sure enough it was negative that I made the call not to invest in it when I was heading OF development 😌

Could we maybe use this issue to collect actual documented use cases of damage occurring because a parameter value was not updated by contributors that make use of them? 🙂

**Comment by maukoquiroga** [comment]
Thanks @MattiSG for that very detailed answer. I agree that we should rather 1) see how countries solve is issue by themselves, if they do, 2) document it as well as impacts, as you say specifically negative —otherwise this would just be a nice to have not solving any important problem.

**Comment by maukoquiroga** [comment]
Closing unless some spec in that sense requires a feature provided by this codebase, or another black swan event.
