### ISSUE TITLE
Missing importlib_metadata requirement

### ISSUE THREAD

**Issue by eraviart** [openfisca/openfisca-core#1176]
Since #1165, `openfisca_core/taxbenefitsystems/tax_benefit_system.py` imports `importlib_metadata`, but that package is missing from requirements in `setup.py`.

So every use of a TaxBenefitSystem fails.

**Comment by MattiSG** [comment]
We also have to understand, as a postmortem, what is missing in the test suite that enabled several versions to be published with such a major problem.

**Comment by maukoquiroga** [comment]
@MattiSG I will push a fix, yet it is IMHO incorrect to label it as a regression, as it is a problem caused by an external change in dependencies.

In fact, just reverting would still make flake8 to fail because of incompatible versions with twine (keyring) as @eraviart reported.

It's hard to provide an analytical postmortem at this point, as most of what is happening seems related to  poor dependency management and very old code (pkg_ressources use had to be refactored, it is not a nice to have).

Concerning #1168, it includes one possible fix for this, but changes were requested because of the publishing job failing (thanks for testing) so it invariably requires a new review.

**Comment by maukoquiroga** [comment]
> We also have to understand, as a postmortem, what is missing in the test suite that enabled several versions to be published with such a major problem.

I think the best solution is to manage build, test and deploy dependencies in isolation. #1161 goes in that direction.

However, it seems unlikely to avoid this 100%, but that would make a great difference IMHO.

**Comment by maukoquiroga** [comment]
After taking a closer look, #1165 did actually broke builds under some configurations, in particular in python versions 3.8+, the culprit being a failure to declare a dependency that was being overridden by others in a least two scenarios:

1. Installing dependencies outside of the setup.py that had `importlib-metadata` as a transitive dependency
2. Using the deprecated legacy resolver to install dependencies.

The direct postmortem I can draw now, with a better distance from the issue:

1. Using libraries without having them declared in an explicit way in the setup.py
2. Not testing in CI against the affected versions of python
3. Installing libraries outside of the setup.py
4. Caching together libraries inside and outside of the setup.py
