### ISSUE TITLE
[CLOSED] Missing parameters

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#314]
_Issue by **[bouvard](https://github.com/bouvard)** from Friday Feb 21, 2014 at 15:58 GMT_
_Originally opened as https://github.com/openfisca/openfisca/issues/315_

---

In openfisca-core: add a mode to run with missing parameters by taking the most recent value of the parameter to replace the missing ones.
Add a log.erro that lists the missing parameters

**Comment by adrienpacifico** [comment]
Hi, 
It does not seem to be implemented (anymore ?). 
* In 2005, If I do :  `simulation.calculate("aides_logement", "2005")`, I get the correct result.
* In 2004 if I do : `simulation.calculate("aides_logement", "2004")` I get:
```python
---------------------------------------------------------------------------
ParameterNotFound                         Traceback (most recent call last)
<ipython-input-130-f3d0e0a22385> in <module>
----> 1 simulation.calculate("aides_logement", "2004")

[...Some long stack trace...]


ParameterNotFound: The parameter 'cotsoc.gen[smic_h_b]' was not found in the 2001-01-01 tax and benefit system. 
```

Would be nice if openfisca took the 2002-01-01 value, printed me a warning that it is not the good value that has been taken for that parameter, and that incentivize me contribute by putting the correct value in the code !

@Morendil

**Comment by Morendil** [comment]
I'm not sure I understand what's going here. Why is an error arising for a lacking value in 2001 when you requested a calculation for 2004? Did we go back to the n-3 salary?

If so, why would we take the 2002 value if the one requested is for 2001? I mean, I'm not sure we can automatically calculate that it's OK to take a *later* value when an *earlier* one was requested. 

We do the inverse, if you request a *later* value and an *earlier* one exists, because we assume that a parameter by default stays unchanged by law. (That assumption is sometimes problematic, for instance for parameters which we know evolve every year. If you're requesting the 2019 value but it doesn't exist, that would be because the parameter base is out of date; the assumption that it hasn't changed is incorrect in that case.)

Also, what if we have values for 2002 and 2004 but not for 2003, and we request the 2003 value? It's very hard to "do the right thing" then because your suggestion above says we should take the later value, but the current behaviour is that we take the earlier value.

> incentivize me contribute by putting the correct value in the code

Possibly, an exception is a stronger incentive than a warning… I'd be afraid, if we only had a warning, that people would trust the result without looking at the logs and the warning. (Similar to a discussion we had on Slack today about role values…)

**Comment by adrienpacifico** [comment]
I must be tired, I mixed *most recent* and *oldest*... Sorry.

Concerning the`calculate("aides_logement")`,  I think that it uses n-3 value of the smic (on n-2 income).

> Also, what if we have values for 2002 and 2004 but not for 2003, and we request the 2003 value? It's very hard to "do the right thing" then because your suggestion above says we should take the later value, but the current behaviour is that we take the earlier value.

Is it likely to happen? It could prioritize to the earlier or the later in case of (unlikely to me) conflict.

> Possibly, an exception is a stronger incentive than a warning… 

Exception will lead me to have no results on my simulations.   

Two likely scenarios to me:
* Objective--> problems-->no results --> rage quit OpenFisca.
* Objective --> problems --> results --> iteratively solve problems to improve results
---
Also in the later case: problems--> Warning all the time --> fed up with the warning --> solve the problem.

Best of both world would be an option to use earlier value displayed to the user when the `ParameterNotFound` exception is raised.


As it is not very important for me now, and maybe a bit specific to users that want to go back in time, I am not asking for that feature for now! (and we can let that old issue to rest in peace ✞).
