### ISSUE TITLE
Programmatically get parameters for formula

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#323]
According to the [`to_json` code](https://github.com/openfisca/openfisca-core/blob/8ec7b27357f19fb151d77f4b89b7658dd17ba22b/openfisca_core/formulas.py#L158-L174), I expect the `to_json()` representation of a Formula to contain a `variables` field listing all its direct dependencies.

However, if I call `to_json` on all `model.tax_benefit_system.column_by_name.itervalues()`, I don't get a single `variables` entry.

How can I `.get('variables')` like in [`openfisca-web-site`](https://github.com/openfisca/openfisca-web-site/blob/c54fb67c37b90c5f2d984e05e4b08a13b7f6111f/openfisca_web_site/templates/france/fr/tree/outils/variable.mako#L85)?

**Comment by MattiSG** [comment]
So, if I understood correctly: the `.get('variables')` syntax was available in `v0.4` only, and `master` will soon switch to `v0.5`, with a new formula syntax that disallows static analysis.
To reproduce introspection, an external script will have to be written, based on AST parsing.
This will be done in high priority, starting today.

@eraviart please correct me if I got anything wrong  :)

**Comment by eraviart** [comment]
Since 0.5, the input variables of a formula are no more declared as formula parameters but are called during formula execution.

To retrieve the input variables of a formula you now need formula introspection. I just implemented it in package [OpenFisca-Parsers](https://github.com/openfisca/openfisca-parsers).

This package contains a [module to retrieve the input variables of a column](https://github.com/openfisca/openfisca-parsers/blob/master/openfisca_parsers/input_variables_extractors.py) and a [sample script that uses it](https://github.com/openfisca/openfisca-parsers/blob/master/openfisca_parsers/scripts/extract_input_variables.py).

If you install this package and upgrade OpenFisca-Web-API, the /api/1/field API has also been updated to optionally show the input variables of a formula. For example, for variable "revdisp": http://localhost:2000/api/1/field?variable=revdisp&input_variables=1
