### ISSUE TITLE
Erase formulas from variables in a reform

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#465]
As user who want to write a reform, I want to convert a Variable who has a function to a pure input variable. I thus want to erase its function and it is not possible right now.

I know I can remove and recreate a variable with the same name but it seems to me that this is a quite usual situation that justifies a specific option if a general one is not possible.

cc @fpagnoux @cbenz

**Comment by benjello** [comment]
@cbenz @fpagnoux: i badly need this feature ;-)
Any hint ?

Thanks again

**Comment by cbenz** [comment]
Did you try introducing an input variable in your reform with the same name? Do you have an example source code?

First, try setting `formula = None` explicitly.

We'll could add a helper function named `to_input_variable`, similar to `neutralize_column`.

**Comment by MattiSG** [comment]
User need: https://github.com/openfisca/openfisca-france/issues/705

**Comment by benjello** [comment]
@fpagnoux : I think this is still needed.
When I update a variable which has no formula, it keeps them !

**Comment by benjello** [comment]
May be a `replace_variable` method is needed to complete the portfolio of tools to build a systematic reform. It would not only update but remove the variable and create a new one.

**Comment by fpagnoux** [comment]
> When I update a variable which has no formula, it keeps using those old formulas !

I think it's not a bug, but a feature 😅. `update_variable` makes a lot of effort so that all the attributes of the variables being updated are kept. They are only modified if overridden in the new variable, including formulas.

I think the point of this behavior (which has been around for longer than me) is to avoid repeating attributes when defining a reform, and to allow to change only the most recents formulas.

Creating a `replace_variable`  methods sounds good to me.

**Comment by fpagnoux** [comment]
PR opened: https://github.com/openfisca/openfisca-core/pull/689
