### ISSUE TITLE
Define currencies as legislation parameters

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#477]
Moved from https://github.com/openfisca/openfisca-france/issues/173.

Currencies are year-dependent, and are currently defined as runtime constants. They should be “well-known” legislation parameters (or metadata), so that they can also be exposed through the API.

**Comment by MattiSG** [comment]
In this issue, the idea was that each country package would have a “well-known” currency parameter that would be valid for all values at some given point in time.
Considering https://github.com/openfisca/openfisca-core/pull/681 and https://github.com/openfisca/openfisca-france/pull/1022, I am not certain this is what we really want. We seem to be more headed towards defining the `unit` at a parameter and variable level.
How can this work for elements whose unit change over time? For example, values that changed from being expressed in `FRF` to `EUR` when France moved from Franc to Euro.
Are we aiming at `unit` being a property for each _value / formula_ rather than each _variable / parameter_? How could that be implemented for formulas? 😥

cc @fpagnoux @benjello

**Comment by benjello** [comment]
The official currency of a country is actually a parameter of the legislation: at some point in time the currency of a country is defined.
Variable and parameters have units. It it is a monetary amount, its unit can be the official currency or another value expressed in monetary amount (for France think of SMIC, plafond de la sécurité sociale).
So may be unit can other parameters of the legislation and one of the can be the official currency.

I am more for a unit at the _variable / parameter_  rather than the _value / formula_  to avoid too much repetition. For complex parameters like scale, the unit could be more structured, for example a dictionary of the components (thresholds, rates).

**Comment by MattiSG** [comment]
> I am more for a unit at the variable / parameter rather than the value / formula

Me too.

But then, how do we define the unit of a value that is expressed in currency, and that survives an official currency change? For example, what should be the `unit` of `bareme_ir` in France? If we define the unit at the parameter level, then I see only two solutions:

1. Use `currency` rather than `currency-EUR` or whatever, and leave it to the country to define what was the currency in use at some point in time.
2. Split `bareme_ir` in two (possibly three if time is extended before the “new Franc” period) variables, one for each currency.

**Comment by benjello** [comment]
I prefer to use 1.

**Comment by Morendil** [comment]
This seems to have been resolved _de facto_ in exposing currencies as [metadata of parameters](https://github.com/fpagnoux/baremes-ipp-yaml/blob/master/openfisca_baremes_ipp/parameters/chomage/allocations_assurance_chomage/ass.yaml). The CURRENCY constant in TaxBenefitSystem seems unused anyway, but also harmless to keep around.

Closing as not requiring further action.
