### ISSUE TITLE
Prevent false negatives in Circle tests on master branch

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#513]
If we rebuild a Circle CI master build, it [turns red](https://circleci.com/gh/openfisca/openfisca-core/90).

This is due to the fact that we try to tag the commit with a label that already exists.

~~This is due to the fact that we wrongfully check that the version has been bumped~~.

~~Suggested implementation: don't run the script `check-version-bump.sh` on branch master.~~

**Comment by fpagnoux** [comment]
Something like:
   `if [ $CIRCLE_BRANCH != 'check-version-bump.sh' ]; then run_something; fi`
may do the job

**Comment by MattiSG** [comment]
- If the failure happens because the merge does not change the version number, then it is an issue and we should simply not try to tag nor publish on Pypi.
- If the failure happens because the package has already been published or a tag has already been added, but it was not expected, then we should definitely have a CI failure. This means that rebuilding manually on `master` will yield red if rebuilding a version bump merge. This is accepted as the cost of detecting missed publishes.

So:

- [ ] Try to tag & publish only if there was a version bump.
