### ISSUE TITLE
Document new simulation constructor

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca-core#532]
The new version of the `/calculate` endpoint of the web API has implied a new constructor for simulations in the Python API.

This constructor is currently only visible in the changelog. It should be documented ~~and the previous one deprecated.~~

**Comment by fpagnoux** [comment]
As discussed on slack, it seems early to deprecate the current way of building a simulation in favor of the new one, as we may need to iterate on the latter.

However, it should be clear in the code that the new constructor aims at replacing the former one, so that no developper wonder why there seems to be two ways of doing the same thing.
