### ISSUE TITLE
Define a default definition_period for all the `Variable`

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#536]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I want to migrate [openfisca-france-indirect-taxation](https://github.com/openfisca/openfisca-france-indirect-taxation) and it is painfull to add a `definition_period` to all `Variable` since the are all yearly variables.

### Here is what I suggest

It may be very useful to be able to define a default value for `definition_period` at the `TaxBenefitSystem` level to avoid redfining over and over the same value for all the variables.

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.
- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by benjello** [comment]
@MattiSG @fpagnoux @michelbl @Anna-Livia @sandcha it could be helpful if we reach a consensus on this soon since I am migrating stuff now ;-)

**Comment by benjello** [comment]
**proposition**: add an `default_variables_definition_period` attribute  to `TaxBenefitSystem` defaulted to `None`. When it is not None use it as `definition_period` for any class inheriting from `Variable` when the latter do not define its own `definition_period`.

**Comment by fpagnoux** [comment]
Hi,
If you are stuck and need to quickly add a `definition_period = YEAR` to all your variables, you can research/replace using regexp:

```
(class (?:.)*\(Variable\):)
```
by
```
\1
    definition_period = YEAR
```

I'm not against adding such an attribute to a `TaxBenefitSystem`.

However, I would _not_ be able to tell which is the most reasonable for `france`. The majority of variables are defined for a year, but that's hugely biased by all the ultra-specific tax declaration fiels. Otherwise, social benefits are defined for months, social contributions are mostly defined for months, and income taxes are defined for years, which seems quite balances between the two.

**Comment by benjello** [comment]
I am not in favor of defining one for France since it is better to ask for contributors to be specific on the definition period when the latter is heterogeneous among Variables. but for some system we treat only yearly variables  (openfisca-france-indirect-taxation) and the `definition_period` _per se_ is a bit overkill.

**Comment by sandcha** [comment]
The user can also define a subclass of `Variable` that sets the `definition_period` to a default value. 
As it is linked to Core Variable, it will still get its updates (and imho it's not more specific than giving this value to a `TaxBenefitSystem` variable as it's on the same level of the classes hierarchy).

**Comment by benjello** [comment]
I can definitively monkey patch `Variable` (I won't introduce a new subclass) but I am not sure it is a good practice. You are the real coders ;-)

**Comment by MattiSG** [comment]
If we currently have only one tax benefit system that would benefit from it, moreover one that is not the main model for a country, that's a smell of overspecificity. If we can't use this on France, then I don't think many other country packages would use it either.

It is important for contributability to avoid inferences (think of #460), and to make sure that each variable can be edited in a standalone fashion, so that a new contributor may improve or correct it without understanding the whole tax and benefit system. The more definitions are moved in some global, shared state, the more likely errors are made or uncertainty is added on the local level.

I am not in favour of adding support for a feature that seems quite specific. What is the issue with setting the `definition_period` on each variable? If it's the cost of adding, then the regexp given by @fpagnoux seems to do the job. If it's the repetition of the declaration, I understand it might be frustrating when writing. But as always, remember how many times code is read vs how many times it is written. The cost of adding one line that will be autocompleted by one's editor will easily be reimbursed by the time saved by each new contributor one would have to teach about the tax and benefit system specificities.

Another more technical solution would be to extend the Core `Variable`, as described by @sandcha.

In any case, I don't think the Core should provide an option that increases complexity and has such a strong shoot-yourself-in-the-foot potential :wink:

**Comment by MattiSG** [comment]
Monkeypatching is more dangerous than extending, as you would rely on the internal references and would keep that implicit. With subclassing, you make it explicit you use a modified version, and keep all your changes in a single place. `YearlyVariable` would also be more readable and clear for all parties involved.

**Comment by benjello** [comment]
Well almost all if not all the other systems have a homogeneous  ̀definition_period` !

**Comment by benjello** [comment]
I can definitively go for a `YearlyVariable` subclass but I really think that newcomers usually have a simple `TaxBenefitSystem` in mind and would benefit from defining a `definition_period` at the global level without having to bearing the burden to define a subclass. This is actually an option that can heavily reduce complexity _at the user level_ without limiting usage.

**Comment by benjello** [comment]
I tried subclassing but the following code is not sufficient:
````
class YearlyVariable(Variable):
    definition_period = YEAR
````
since i get:
````
Traceback (most recent call last):
  File "/home/benjello/.local/bin/openfisca-run-test", line 11, in <module>
    load_entry_point('OpenFisca-Core', 'console_scripts', 'openfisca-run-test')()
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/scripts/run_test.py", line 27, in main
    tax_benefit_system = build_tax_benefit_sytem(args.country_package, args.extensions, args.reforms)
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/scripts/__init__.py", line 43, in build_tax_benefit_sytem
    tax_benefit_system = country_package.CountryTaxBenefitSystem()
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/france_indirect_taxation_taxbenefitsystem.py", line 30, in __init__
    self.add_variables_from_directory(os.path.join(COUNTRY_DIR, 'model'))
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/taxbenefitsystems.py", line 204, in add_variables_from_directory
    self.add_variables_from_file(py_file)
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/taxbenefitsystems.py", line 193, in add_variables_from_file
    self.add_variable(pot_variable)
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/taxbenefitsystems.py", line 165, in add_variable
    return self.load_variable(variable, update = False)
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/taxbenefitsystems.py", line 152, in load_variable
    column = variable.to_column(self)
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/variables.py", line 48, in to_column
    raise Exception('Variable {} must have an entity'.format(self.name))
Exception: Variable YearlyVariable must have an entity
````
hints welcome @sandcha @MattiSG @fpagnoux ;-)

**Comment by fpagnoux** [comment]
You probably defined `YearlyVariable ` in the `model` directory. OpenFisca thinks it's a variable of your legislation, and is surprised that you didn't declare an entity for it ;).

**Comment by sandcha** [comment]
Something like

**Comment by sandcha** [comment]
Something like this should work (with `openfisca_core.variables` import): 
```
class YearlyVariable(Variable):

    def __init__(self, name, attributes, variable_class):
        self.name = name
        self.attributes = attributes
        self.attributes['definition_period'] = YEAR
        self.variable_class = variable_class
        Variable.__init__(self, name, attributes, variable_class)
```

**Comment by benjello** [comment]
@sandcha:  the real problem was that the definition of YearlyVariable was in the model.base and thus loaded when initializing the TaxBenefitSystem
