### ISSUE TITLE
Make the API discoverable from the API root

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#615]
Related to #512

**For** developers.

**Stories:**

When I’m considering working with the Web API,
I want to know if I'm in the right place,
so I can continue working without being frustrated.

When I'm working with the Web API,
I want to know the most important endpoints,
and I want to be able to navigate them,
so I can build my app more efficiently.

**Definition of done:**

The idea is to render a helpful response to :

- [ ] Let people know they're in the right place
- [ ] Let people request the root of API to get a list of the most important endpoints

**Comment by Anna-Livia** [comment]
Proposition  when accessing the root of the API: 
{
      "openfisca-country-package" : "country-template-3.12.3",
      links: {
                   "list of all the parameters" : "//parameters"
                   "list of all the variables" : "//variables"
                    "description of a parameter": "//parameter/{name of the parameter}"
                   "description of a variable": "//variable/{name of the variable}"
                   "Calculate variables for a given situation": "//calculate"
                    "OpenAPI specifications": "//specs/"
      }
}

**Comment by maukoquiroga** [comment]
Love the idea (looks a lot like https://api.github.com/).

I would:

- Use the full path, otherwise it won't be truly discoverable
- Only enumerate resources (i.e. `parameters` is a resource, `list` or `calculate` is an operation)

Example:

```json
{
  "info": {
    "country-package": {
      "title": "country-template",
      "version": "3.12.3"
    }
  },
  "links": [
    {
      "rel": "self",
      "description": null,
      "href": "https://fr.openfisca.org/api/v21"
    }, {
      "rel": "parameters",
      "description": null,
      "href": "https://fr.openfisca.org/api/v21/parameters"
    }, {
      "rel": "parameter",
      "description": null,
      "href": "https://fr.openfisca.org/api/v21/parameter/{parameter_id}"
    }, {
      "rel": "variables",
      "description": null,
      "href": "https://fr.openfisca.org/api/v21/variables"
    }, {
      "rel": "variable",
      "description": null,
      "href": "https://fr.openfisca.org/api/v21/variable/{variable_id}"
    }, {
      "rel": "spec",
      "description": "OpenAPI specifications",
      "href": "https://fr.openfisca.org/api/v21/specs"
    }
  ]
}
```

**Comment by Anna-Livia** [comment]
I feel that the `github model` is more readable.

> Only enumerate resources (i.e. parameters is a resource, list or calculate is an operation)
Why ? It seem to me that we have the opportinity to give some context for humans and that is a good thing. at least in the description.

OK on the full URL

Why did you not mention the /calculate root ?

**Comment by maukoquiroga** [comment]
> I feel that the github model is more readable.

Your choice, I changed description so focus is not on HATEOAS but in any form of "discoverability".

> Why did you not mention the /calculate root ?

We should add it, you're right (I thought it was not a good idea, but I slept on it and now I don't see why not).

**Comment by fpagnoux** [comment]
> Let people request the root of API to get a list of the most important endpoints

Thinking more about that, I think we should be careful not to duplicate the `/spec` route and the [swagger](https://fr.openfisca.org/legislation/swagger) doc.

Is listing the routes really useful for the users if we don't tell them which HTTP method to use? They may be confused why the link to `/calculate` doesn't work, as `GET` is not accepted. But does it make sense to mention a `POST` route without document the expected format of the input. I feel like very soon, we'd be either duplicating `spec`, or providing less information.

As a future API user who just ended up on `/api`, I think what would help me the most is:
- Some basic text confirming that I'm in the right place
-  A link to the swagger doc

Maybe something basic like:

```JSON
{
  "welcome": "Welcome to the OpenFisca France Web API! Please checkout the API interactive documentation to learn how to use it: https://fr.openfisca.org/legislation/swagger"
}
```

if a custom message is provided in the server conf. Otherwise we could have a default like:

```JSON
{
  "welcome": "Welcome to the OpenFisca Web API. This API routes are documented using the OpenAPI standard (https://link.to.open/api) here: https://fr.openfisca.org/api/v21/spec
}
```

**Comment by MattiSG** [comment]
In the original #512, we mentioned HATEOAS. It was no accident. It is hard to figure out the proper format and data to send. If you want to have discovery, then it is probably worth implementing [JSON API](http://jsonapi.org/format/#document-links), but I'm not sure just how much it can be useful if the full API is not hypermedia-enabled.
The first propositions read to me as though they would be served with a `application/vnd.api+json` MIME type, but that this endpoint would be the only one to be.

I support the idea of having an “It works!”-style confirmation page rather than a full-blown JSON endpoint.
Reading the user story, a simple text message stating “This is the root of an OpenFisca API. Learn how to use it on openfisca.org/doc/api.` would fit the bill. Using JSON increases consistency and is certainly welcome.
Then again, if you have the time and resources to escalate this to “Let people request the root of API to get a list of the most important endpoints”, that's great! :smiley: This probably needs using standards, though.

There is to me one conceptual point that can make this clearer: do you feel like `/` should be documented as an API endpoint?

1. If yes, then its use cases should be defined, its format should be standard, documented in `/spec`, and should reply with a `200`.
2. If no, then it's just a (welcome!) beacon and it should have a simple phrasing congratulating users for having set up their server and encouraging them to explore the API documentation, and should reply with a [`300`](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/300).

Lacking a larger plan to implement #512, I support option 2.
