### ISSUE TITLE
 Explicit vector computations with pluralized argument name

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#651]
Currently a formula as the following signature

```python
def formula(person, period, parameters)
```

What do you think about using `people` instead of `person` to reflect the vector computation ?

For instance:
```python
def formula(people, period, parameters)
```

**Comment by MattiSG** [comment]
Strong agree.

**Comment by MattiSG** [comment]
@verbman you encountered this issue recently and are a native English speaker, would `people` or `persons` sound more appropriate here, both grammatically and to carry the idea of an array of `person` (as a basic entity)? 🤔 🙏

**Comment by verbman** [comment]
I'm going to recommend `persons`. Technically (historically) the words people and persons aren't related and entered the english language at different times. `people` is supposed to be more used for a larger undetermined number of people whereas `persons` was for a smaller known number. This isn't adhered to nowadays. As `persons` fits the english pattern of adding `s` to indicate the plural of `person` I believe it's descriptively the more elegant choice.

**Comment by benjello** [comment]
As @verbman : i think we should stick to the names of the entities. 
Another point though, should we use singular or plural ?
 - We have a vector so potentially a plural of instances of a particular entity 
 - OTOH the function is valid for every instance of the entity so the entity might be more relevant therefore the singular seems more relevant.

It is the second solution that has been used in France. Another plus: you do not have to think about the plural when it is not just adding an s (foyer_fiscal vs foyer_fiscaux) and you tsop asking yourself should I use singular or plural in this situation.

**Comment by fpagnoux** [comment]
These are really interesting and important discussions.

I think one idea that pushed towards using singular variable names was an attempt to partially _hide_ the vectorial complexity to the user. The idea being: 
> "Many calculations will work as expected without worrying too much about what `person` _is_ exactly. Let's not bother the user with that, _until_  they reach more complex usecases where they will need to understand more about the internal vectorial nature of the computations."

What I'm hearing from different sources here is that this idea doesn't really work, because users are _very quickly confronted_ to these more complex use cases. So it would be better to be honest about it from the beginning, and not try to hide that they are handling vectors.

**Comment by fpagnoux** [comment]
Some suggestions:

Easy ones:

- Using a plural argument name
   - This is not directly set in core, because `persons` is a dummy variable. You can call it whatever you want when coding formulas.
   - However, all examples in the doc should be updated
- Using a plural key to access the entity array from the `simulation` object (in the Python API)
    - `simulation.households` rather than `simulation.household` 

More advanced:

- Change the type of `persons` to reflect more its vectorial nature
    - Right now, `persons` is an instance of `Person`. Should probably be an instance of `PersonArray` instead.
   - Slightly change the API of this class to be more vector-like. For instance:
        - Expose the number of persons with `len(persons)` rather than `persons.count`
        - Change the representation (what is printed if I type `persons` in an interactive python console) to something like `PersonArray(['Alice', 'Bob', 'Claudia'])`

Would you think these changes would be useful for newcomers on-boarding?

**Comment by fpagnoux** [comment]
A quick technical note though:

`persons('salary', period)` is a numpy array, but `persons` is **not**. You **cannot** pass it as the `a` argument of a numpy function. 

Numpy arrays are low-level objects. Our `persons` need to be able, among other things, to calculate any variable from the tax and benefit system. A numpy array would not be able to do that 😅 .

So the best we can do  is to change the nature of `persons` so that it _represents_ the concept of an array of persons, but it will not _be_ and array of person.

**Comment by MattiSG** [comment]
> the conclusions of your experiment with Aotearoa will be precious. Did you reach any yet?

Partially. You can see examples of using plural entities parameters [here](https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/master/openfisca_aotearoa/variables/rates_rebates.py#L68-L78).
Unfortunately, since the documentation and country-template had singular examples, it was hard to test the practice with newcomers at the hackathon.

[One team](https://github.com/ServiceInnovationLab/openfisca-aotearoa/pull/17/files#diff-b602728f37a55cd90e301d288a1e858cR38) did use it, but they were helped by @verbman, so we cannot conclude on their understanding of vectorial computing. That still gives another code example to read through.

[Another team](https://github.com/ServiceInnovationLab/openfisca-aotearoa/pull/16/files) used plural. @nigelcharman, if you had any feedback on defining `formula(persons, period, parameters)` (with `persons` being a plural) and if you believe that helped in writing vectorial calculations, it would be awesome!

- - - -

> this idea doesn't really work, because users are very quickly confronted to these more complex use cases

👍
And I find that it is actually very frustrating for someone new, who thought they were finally understanding that OpenFisca thing, that there is just _this little thing_ that ruins all their efforts at writing a formula. I don't think we can shield users from it: either they don't have to write or read formulas and they thus don't need to learn about it at all, or they have to and we'd better make it easier to respect the constraints.

- - - -

### Does anyone have a strong opposition to stopping hiding vectorial computation constraints to new users?

If not, I'd like to proceed and start an RFC 🙂

**Comment by nigelcharman** [comment]
@MattiSG - yes we were stumbled for 5-10 minutes by vectorial calculations. We saw an error message similar to `The formula 'tax_rebate@2018' should return a NumPy array; instead it returned '1000.0' of type 'float'.` Having that error message included in OpenFisca documentation was a godsend, since a Google search quickly found that. The documentation was then quite easy to follow for our use case.

One area that we did trip up on was calling a method from another method (for example calling `weekly_compensation_before_tax().formula(persons, period, parameters)` from `kiwisaver_employee_deduction().formula(persons, period, parameters)`. I don't know if this is due to vectorial computation being used or is a more generic lack of knowledge on our part? If the former, it would be useful to add this case to the documentation.

**Comment by MattiSG** [comment]
> calling a method from another method

These are actually not methods but formulas of variables. There is no support for factoring code this way in OpenFisca, because variables model legislation, and legislation does not factor its computation formulas: it either duplicates formulas or reuses the result of another one. Variables align with this behaviour.

> The documentation was then quite easy to follow for our use case.

🎉 https://github.com/openfisca/openfisca-doc/pull/134 proven right

**Comment by MattiSG** [comment]
RFC opened at https://github.com/openfisca/openfisca-core/issues/673.

**Comment by Morendil** [comment]
Closing as stale, see #673 closing comment.
