### ISSUE TITLE
Deprecate Python 2.x

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-core#693]
As per python/devguide#344, Python 2 will be sunset come Jan 1st, 2020.

Additionally, a number of projects used in conjunction with OpenFisca [have pledged to stop supporting Python 2 soon](http://python3statement.org/) :

- pandas
- Matplotlib
- NumPy
- Jupyter notebook

Notably, NumPy's Python 2 maintenance mode will start come 2019.

Let's open the discussion and tackle this effort together.

To-do:

- [x] Change CircleCI configs
  - [x] Core uses 3.7
- [x] Change READMEs
- [x] Edit doc
- [x] Shared in Slack #general (YouTube, future, ...)
- [x] Tweeted
- [x] Sent by email

---------
_EDIT by @fpagnoux_:

Todo on January 1st:
- [ ] Remove all the `from __future__`, `from builtins` and `from future` imports

**Comment by benjello** [comment]
At IPP, we will be happy to participate to the big switch, but we will be ready to do that around next december ...

**Comment by fpagnoux** [comment]
Shall we announce the end of Python 2 compatibility for January 1st 2019 then? 

It seems a reasonable amount time for re-users to adapt their code?

**Comment by benjello** [comment]
@fpagnoux : I am not against having a strong deadline. 

The best way to keep every contributors happy to reach it might be helping them to go through the necessary steps to transition to Python 3.

One point thought, using Python 2 until jan 2019 should be possible. And so the best way is having code supporting both Python until then.

Since @Anna-Livia and you went through the process, could you list somewhere if it is not to cumbersome the necessary steps to go through and I will definitively try to use that info to update IPP codebase and other packages like openfisca-survey-manager and openfisca-france-indirect-taxation (wich is BTW laggard in core too)

**Comment by guillett** [comment]
@jmdallais, @Lashchuk , @ThibaultCCMSA , @SChiusa , @JenniferTelep , @LacombeEric, @frtomas , @mtifarine , @marchand-laetitia-msa, would you be able to move PNDS servers to Python 3 before early 2019 ?

**Comment by jmdallais** [comment]
@guillett thanks for sharing.
@tchabaud, could you answer to @guillett please ? Strong prerequisites or constraints for us ? 
Give me a call tomorrow please.

**Comment by fpagnoux** [comment]
> One point thought, using Python 2 until jan 2019 should be possible. And so the best way is having code supporting both Python until then.

Right now, the code is tested to run both in Python 2.7 and 3.6. So no worries until January!

> Since @Anna-Livia and you went through the process, could you list somewhere if it is not to cumbersome the necessary steps to go through and I will definitively try to use that info to update IPP codebase and other packages like openfisca-survey-manager and openfisca-france-indirect-taxation (wich is BTW laggard in core too)

Yes, we can work on some documentation to support re-users migrations. We are right now [still learning](https://github.com/openfisca/openfisca-core/pull/702) how to do it best, but we'll share recommandations when we have stronger convictions. 

If I can recommend two things to get ready to migrating your codebase:
- Add unit tests so that you'll be able to identify issues quickly
- Watch this talk: https://www.youtube.com/watch?v=klaGx9Q_SOA

**Comment by tchabaud** [comment]
Hello @jmdallais @guillett 

Migration delay to switch to Python 3 seems really feasible, but I need to check with technical teams.
I'll let you know when I getan answer from them.

**Comment by tchabaud** [comment]
@guillett : we plan to take advantage of the python 3 switch to get rid of the apache / mod_wsgi stack we're currently using to serve openfisca on our infrastructure.

Which python webserver would you advocate to replace this stack ? Which one do you use in production ?

**Comment by guillett** [comment]
We use gunicorn and nginx in [MesAides](https://github.com/sgmap/mes-aides-ops).

**Comment by tchabaud** [comment]
@guillett : is it possible to directly switch to a Python 3.7 interpreted or is it too risky at the moment ?

**Comment by guillett** [comment]
@tchabaud I don't understand your question. Please feel free to call me next week.

**Comment by tchabaud** [comment]
@guillett : I just wanted to know if we could install openfisca on a 3.7 python interpreter instead of a 3.6. According to this [comment](https://github.com/openfisca/openfisca-core/issues/693#issuecomment-409987417) it seems to be only tested with 3.6.

**Comment by fpagnoux** [comment]
Everything seems ready, we just need to wait for January 1st to:

- [ ] Shut down Python 2.7 releasing
- [ ] Remove backward compatibility code 
     - [ ] Remove all `from __future__`, `from builtins` and `from future` imports
     - [ ] Remove other adaptations

**Comment by maukoquiroga** [comment]
Thanks @fpagnoux 👍. I'll create another issue to track down shut down and close this one.
