### ISSUE TITLE
Improve aggregation syntax

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-core#725]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

I would like to use a more laconic aggregation syntax than [the one present in the doc](https://openfisca.org/doc/coding-the-legislation/50_entities.html).

Actual:
````
salaries = household.members('salary', period)
sum_salaries = household.sum(salaries)
````

Potential improvement:
````
sum_salaries = household.members('salary', period).groupby('household', sum) 
````
or even shorter
````
sum_salaries = household.members('salary', period).groupby('household').sum() 
````

Inspiration comes form [pandas](https://pandas.pydata.org/pandas-docs/version/0.23.4/groupby.html#groupby-sorting).

## Context

I identify more as a:

- Analyst _(I make macroscopic computations on real populations)_.

**Comment by benjello** [comment]
@fpagnoux @sandcha : I assigned you to foster discussion !

**Comment by maukoquiroga** [comment]
Hello @benjello, thanks for your contribution.

If the result of:

```python
household.members('salary', period)
```

is a `numpy.ndarray`, then in order to get a syntax like:

```python
array.groupby(key)
```

one would have to attach as a method the wanted function. In NumPy we could accomplish that with a view, i.e.:

```python
import numpy


class GroupableArray(numpy.ndarray):
    def groupby(self, key):
        print("Hello Mehdi") # replace with groupby algorithm, returning a NumPy array


array = numpy.array(data).view(GroupableArray)
array.groupby(key).sum()
```

Of course, you need to define your grouping algorithm (Panda's not going to work as it requires a `DataFrame` instance). You may want to take a look at [this](https://github.com/EelcoHoogendoorn/Numpy_arraysetops_EP/blob/master/numpy_indexed/grouping.py).

That would be, IMHO, more a NumPy extension than an OpenFisca API addition.

Does this answer responds to your initial question?

**Comment by benjello** [comment]
You have a good point we produce numpy arrays that do not have a clue about their entity and its index. May be we should have a class inheriting from numpy arrays with this additional information son they can have extended méthodes like groupby etc

**Comment by maukoquiroga** [comment]
Hi @benjello, we could effectively package a NumPy extension with a function like groupby. Question is if you have the algorithm already in mind ? I ask because it seems to be an expensive operation performance-wise.

@fpagnoux told me something like this has already been done for `Enum`s. What do you think?

**Comment by benjello** [comment]
I do not understand the performance concern. Do the usage of a subclass of numpy array very expensive ?
We just need an entity attribute and a few simple methods.

I won't say it is urgent (reflexion on entities and links to define them is more fundamental IMHO) but it is more elegant and more pythonic than the tedious way we employ right now.

**Comment by maukoquiroga** [comment]
> I do not understand the performance concern. Do the usage of a subclass of numpy array very expensive ?

No, what I mean is that the `groupby` algorithm itself could be expensive.

There're in fact two things here:

1. Implementing the algorithms themselves.
2. Extending NumPy array

We've been discussing about 2).

**Comment by benjello** [comment]
@maukoquiroga : well the algorith is mainly what we already do by hand ...

**Comment by fpagnoux** [comment]
Sorry, I've been willing to look at this issue for a while, but didn't find time.
I thought about simplifying aggregation some time ago (I agree the current way is a little heavy), so I can share some ideas by the end of the week.

**Comment by maukoquiroga** [comment]
Hi, thanks @fpagnoux, I do not know why I suddenly thought what we wanted to do was to implement something of the kind of `pandas`, and I just realise the "algorithm" is already in the description of the issue , sorry @benjello.

In the light of my initial comment, I think this is the more natural way for it to look :

```
sum_salaries = household.members('salary', period).groupby('household').sum() 
```

I mentioned sub-classing but I imagine there are other strategies to achieve the same result.

**Comment by fpagnoux** [comment]
A change was would not cost much and allow a relatively clear one-liner would be to allow:

```py
household.sum('salary', period)
```

**Comment by benjello** [comment]
@fpagnoux : if we can add a roles option too it would be very nice.

**Comment by fpagnoux** [comment]
Now, if we want to be more prospective, some thoughts:

The ability to be able to "group by" is definitely interesting. But it brings some challenge

###  1. The matrix

`salaries.groupby('household')` (or whatever other syntax we use to get an object on which we can `.sum(), .any()` ) is probably a 2-D matrix. 

Each column represents a household in the simulation, and each line is the value of `salary` for the `ith` person of each household.

One issue is that not all households have the same amount of people. If I have two families with respectively 2 and 1 people, then the matrix would look like:

```
      [[2000, 3000],
       [2500,    X]]
```

Now, question: what do we put instead of `X` ? `0` is tempting, and works well for `sum`, but things get tricky for different kind of aggregation.

For instance, if we choose `0` as a default value, `salaries.groupby('household').min()` is `[2000, 0]`, which is _not_ the minimum salary in the household! (That would be `[2000, 3000]`). 

The default value that should be used during an  aggregation depends on the operation we use to aggregate. So this matrix must know which of its values are irrelevant. There are solutions, but they all imply that the matrix is a custom subclass of numpy arrays, which brings some complexity.

**Comment by fpagnoux** [comment]
> @fpagnoux : if we can add a roles option too it would be very nice.

Yep, the roles option would be kept.

**Comment by benjello** [comment]
@fpagnoux : we can use `nan` for X and use the numpy functions that handle it correctly like for example [`nan`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.nanmax.html)

**Comment by Morendil** [comment]
I'll have a proposal next week to address this - as I understand the underlying need - at a somewhat higher level than "syntax". Stay tuned. :)

**Comment by fpagnoux** [comment]
@Morendil are you still planning to suggest a proposal on this?

**Comment by Morendil** [comment]
Yes. The code is written up, I need to have enough of my and the team's time to introduce and explain.

**Comment by benjello** [comment]
@maukoquiroga : there a quite a lot of places ([example](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/mesures.py#L60)) where we have the two steps syntax described in the first post of this issue.

**Comment by benjello** [comment]
But I do not see this problem as urgent but it causes troubles to new users.

**Comment by Morendil** [comment]
See #874 and #890 for newer ideas; I'm going to close this as we haven't made progress on the specific proposal here.
