### ISSUE TITLE
Expose variable source extension in Web API

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#750]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
Create a [test generator (from JSON payload)](https://github.com/betagouv/mes-aides-ui/blob/master/backend/lib/openfisca/test.js).

### Here is what I expected to happen:
Not to have [to explicit](https://github.com/betagouv/mes-aides-ui/blob/master/backend/lib/openfisca/test.js#L36-L56) the origin of the variables.

Specifically, I expected https://openfisca.mes-aides.gouv.fr/variable/parisien to contain
```json
"origin" = "openfisca_paris"
```

### Here is what actually happened:
I had to explicit the origins.

## Context

I identify more as a:

- Developer _(I create tools that use the existing OpenFisca code)_.

**Comment by guillett** [comment]
Up @openfisca/core-contrib

**Comment by Morendil** [comment]
This may be trickier than it looks, because extensions don't exist. By which I mean, they're not reified as a class in Core (see [this gist](https://gist.github.com/Morendil/8ac4d09490db0769f524ad0cb97e3b99) for an overview of Core classes from an implementation POV). The entry point is method `add_variables_from_directory` in TaxBenefitSystem.

One quick and dirty solution would be to add an `extension` keyword arg to that methods and its callees, defaulting to None, and enrich the Variable instances with an extension field indicating the origin extension. It's then relatively straightforward to expose this field in the API.

I anticipate that it won't be super easy to unit test at an appropriate level, because of the way variables are implemented, as Python classes grouped into modules. This means that the TaxBenefitSystem methods that load classes are relying on side-effects and details of the module system.

An implementation looking more at the long term could look into decoupling Variable instance data from the Python methods that make up their formulas. This would be way more testable. Instead of Variable subclasses, I think the long-term maintainability of OF would be better served by using plain instances of the Variable class. There are other ways of loading Python methods or functions and associating them with these objects.

@fpagnoux WDYT ?

**Comment by sandcha** [comment]
@guillett Do you have some time in the next few weeks to show me how you work with extensions?

**Comment by guillett** [comment]
Yes, what do you want to know exactly ?

You can have a look at https://github.com/betagouv/mes-aides-ui#openfisca to have a working setup on your workstation.

**Comment by MattiSG** [comment]
@guillett this issue has not seen discussion in 30 months. Is this still valid for you?

If yes, could you please make more explicit what the use case is? I understand that you would like to know over the Web API in which extension a variable has been declared, but I don't understand _why_ you need that information 🙂

**Comment by MattiSG** [comment]
Assuming this is not relevant any more, closing.

Feel free to reopen / comment if this is still relevant! 🙂
