### ISSUE TITLE
Make API boot faster

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-core#792]
As @guillett mentioned recently, the API start has become really slow:

![capture d ecran de 2018-12-03 21-34-27](https://user-images.githubusercontent.com/1410356/49400036-55411c00-f743-11e8-9465-6ec83cce2654.png)

There seems to be room for improvement, as a lot of the costly operations run during boot are not always necessary. We should  probably make the API lazy and:

- Load a variable's source code only when requested
- Run the calculations needed for the `/spec` examples only when this route is called.

**Comment by maukoquiroga** [comment]
Note: to test how this would impact request response time.

**Comment by Morendil** [comment]
Closing this as stale.

@guillett As you were mentioned, I'd like to help with this if you feel that decision doesn't serve your needs. In particular feel free to reopen, but if you do, please accept the following challenge to the problem statement:

For an API server to have a warm-up time of 20s as a cost of having immediate response time to all queries strikes me as perfectly reasonable; these processes stay up a long time.

The API boot time may seem expensive **because you experience it it in a different context than spinning up an API server**, for instance you have a development feedback cycle that requires you to code something, fire up the API, check how it behaves, and repeat the process. I would argue that the problem is not with the boot time but with the development process. I'm willing to make time to discuss this.

**Comment by sandcha** [comment]
Note for later: At Web API loading, multiple calculations are executed for simulation examples (code examples used by `swagger`. These examples impact the loading time for all users.
> See `loader/__init__.py` > `build_data(tbs)` that leads to `spec.py` > `build_openAPI_specification(api_data)`  which, in case of a simulation example, runs `handlers.calculate(...)` and `handlers.trace(...)`.

**Comment by Morendil** [comment]
Also to record an idea from IRL discussion with @sandcha on this, as we were iterating on a support task and something like the following loop:
- insert debug print statements into formula or Core code to test a hypothesis
- fire up France API with `openfisca serve --workers=1`
- throw a JSON payload at it with `curl -X POST -d @payload.json` etc.
- look at results of print statements
- try another hypothesis, which needs a code change or more print statements
- repeat

This is definitely "a different context than spinning up an API server". We do it and suffer the 20 second iteration penalty because
- the user who called on the Slack support channel provided a JSON payload
- converting a JSON payload to a YAML test would be time-consuming
- converting a JSON payload to a YAML test could easily have masked the problem

So a much better solution here would be to allow a command line entry point such as

```openfisca api calculate payload.json```

which would ingest the JSON file, invoke the `calculate` (or `trace` or other handler), while skipping all the heavy lifting that goes on at API startup.
