### ISSUE TITLE
Improve reform usage documentation

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#804]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
I create a simulator based on OpenFisca. OpenFisca represents the official legislation. For a simulator, assumptions have to be made to provide meaningful information. Instead of embedding those hypothesis in my application, I thought it would be better to have them in a reform (testability, reusability, etc.)

### Here is what I expected to happen:
I want to update variables to use the value on a specific period for multiple periods (for instance, use the salary provided for 2018-12 for all the previous periods).

I [hacked a reform together](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/reforms/simulation_reform.py#L14-L32) but I wanted to create a reform as:
```python
class simulation_reform(reforms.Reform):
    class date_simulation(Variable):
        value_type = date
        entity = Individu
        label = u"Date de la simulation"
        definition_period = MONTH

    def apply(self):
        self.add_variable(self.date_simulation)

        baseline_aah = self.baseline.get_variable('aah')
        class aah(Variable):
            def formula(individu, period):
                # Si l'évaluation est nécessaire utilise,
                # si possible, le montant de la période de simulation
                known_periods = individu.get_holder('date_simulation').get_known_periods()
                if known_periods:
                    date_demande = sorted(known_periods, reverse = True)[0]
                    formula = baseline_aah.get_formula(date_demande)
                else:
                    formula = baseline_aah.get_formula(period)

                return formula(individu, period)
        self.update_variable(aah)
```
I managed to put this reform together thanks to @claireleroy and @benjello but it is undocumented.

![img_8340](https://user-images.githubusercontent.com/1410356/50478425-4dd30280-09d1-11e9-8209-fdf9e9a53f27.JPG)

**Comment by Morendil** [comment]
"Undocumented" is too mild a word. This is also untested and therefore quite brittle. Formulas are not regular functions or methods; I suspect there's a very high probability that future changes in Core will cause your code to break if you obtain a formula via get_formula and call it yourself. Even without Core changes, if the baseline `aah` variable's formula is ever modified to use a parameter, your code will break because it does not supply parameters.

I'm not sure I completely understand what you're trying to do, I'm interested in knowing more about the context. I have a strong hunch that there's a simpler way to do it, and one that will be less vulnerable to future breaking changes.

Modeling `date_simulation` as an input variable means that it may have different values for different individuals. However, in your code, you're discarding the individual values and instead selecting a formula based on the latest date for which `date_simulation` is known. I don't understand the intent of this.

Without necessarily providing a full YAML or JSON payload, can you sketch for me a sample test case and what you expect the result to be ?

**Comment by guillett** [comment]
Many thanks @Morendil for your regular prompt answers!
This snippet is actually not working (cycles are back) and an ugly hack.

I will try to explicit my use-case here soon to make sure we have a common understanding of the objective.

**Comment by fpagnoux** [comment]
> Formulas are not regular functions or methods; I suspect there's a very high probability that future changes in Core will cause your code to break if you obtain a formula via get_formula and call it yourself. 

Just FYI, right now variable formulas are actually regular functions, with no added magic. 

> Even without Core changes, if the baseline aah variable's formula is ever modified to use a parameter, your code will break because it does not supply parameters.

That risk would be easily avoided by passing the `parameters` argument when calling the baseline `aah` variable.

**Comment by Morendil** [comment]
@guillett Should we close this issue?

**Comment by Morendil** [comment]
Closing. Correct me if I'm wrong @guillett but I see a link between this and what we discussed IRL around being able to transform a time series of a discrete variable with values at different dates, into a date-valued "signal" of the transitions of this variable. This is an interesting and challenging idea, but I don't think this issue conveys it and I prefer to close while we discuss it.
