### ISSUE TITLE
Return the symbolic values of Enums in /trace and print_com putation_log rather than integers

### ISSUE THREAD

**Issue by magemax** [openfisca/openfisca-core#822]
The trace for strings that belong to a limited list of values appear in the trace as a number instead of a string.

For example, a test that involves computing the family situation of 3 people can look like this :

   statut_marital<2017-01> >> [5 5 5]

While it could be  clearer to show 

   statut_marital<2017-01> >> [pacse  pacse  pacse]

("pacse" being the 5th value of the enum according to the documentation : https://fr.openfisca.org/legislation/statut_marital?q=statut_marital   )

Note that this problem seems to affect both the trace made in python (using the command  "openfisca test  myyaml.yaml -v",  and the tracer tool that appears in another git https://github.com/betagouv/openfisca-tracer

The problem can be reproduced by running a test on the following yaml : 

[cpleyaml.txt](https://github.com/openfisca/openfisca-core/files/2837276/cpleyaml.txt)

**Comment by Morendil** [comment]
> this problem seems to affect both [python trace and API trace]

It does, but not because they're backed by the same implementation; we have two:
- the `/trace` API endpoint relies on `Tracer::print_trace` and the internal structure `trace`
- the internal call `print_computation_log` relies on the internal structure `_computation_log`

@sandcha @fpagnoux Do you have insights into why historically we ended up with these two (apparently redundant or at least overlapping) data structures ?

Variables that carry enumerated values will appear as instances of `EnumArray` rather than as instances of NumPy arrays, this class is related to the `Enum` class defined in `indexed_enums.py`. `EnumArray` has a couple methods `decode(_to_str)()` that decode the underlying representation (a NumPy array of integers) to the symbols or their string representations.

The handler for the /trace endpoint contains code that appears to attempt this conversion:
https://github.com/openfisca/openfisca-core/blob/780ba969a656cca73559a53cc6528aeb383a92aa/openfisca_web_api/handlers.py#L56-57

However, this code doesn't work as intended; it tries to filter for instances of Enum but I think it should have a condition on the entire vector value being an instance of EnumArray, rather than testing the first value of the array.

The following test fails (added to `tests/web_api/test_trace.py`):

```
def test_trace_enums():
    new_single = deepcopy(single)
    new_single['households']['_']['housing_occupancy_status'] = {"2017-01": None}
    simulation_json = json.dumps(new_single)
    response = subject.post('/trace', data = simulation_json, content_type = 'application/json')
    assert_equal(response.status_code, OK)
    response_json = json.loads(response.data.decode('utf-8'))
    disposable_income_value = dpath.util.get(response_json, 'trace/housing_occupancy_status<2017-01>/value')
    assert disposable_income_value[0] == 'tenant'  # The default value
```

If you're interested in contributing to OpenFisca Core this would make a good first PR. Otherwise, we can plan to take this on in one of the next few development iterations; it would fit the "improvements in usage of Legislation Explorer" theme or the "improved debugging" theme. (Poke @sandcha)

**Comment by Morendil** [comment]
@magemax (I've taken the liberty of rewriting the issue title; for issues, we like to use the imperative and describe what OpenFisca should do after fixing the issue: this makes it easier to come up with descriptions of the change in the same format for the CHANGELOG.)
