### ISSUE TITLE
Enable group entities addition via extensions and reforms

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-core#851]
Local legislations can rely on specific relationships between people.

I would like to separate that complexity for a given country model and build logic on top of a country package.
Would that be possible ?

The logic I would like to represent is, in French, "les obligés alimentaires" for a given person. A group entity with a main role subject (n=1) and relatives (n=N) would capture that complexity.

Maybe a start would be to implement that as a POC in a France model branch/fork. WDYT ?

**Comment by benjello** [comment]
This is a strong limitation of openfisca.
I thinks we should think about having "dynamic entites".
 - We could have many atomic entites, says individual, entreprise, dwelling.
 - We could links between this entities: mother, house etc
 
We can thus define the collective entity building on these relation.
Say the head of a tax household (foyer fiscal) is the everybody who is less than some age and not the child of someone else alive, have no spouse earning more than him, the second earner etc.
So we could define the relevant entity for every benefit or tax. 

We could have many salary etc.

But it is a huge work !

**Comment by Morendil** [comment]
Thanks for the suggestion @guillett. We've not made progress on this issue, and based on @benjello's response the scope appears too broad to manage well. So I'll close this for the time being.

My suggestion would be to open an issue on France asking for ideas on representing the specific legal concept you're interested in ("obligés alimentaires") *without* presuming anything about the technical solution. Maybe it's reform-based entities, maybe we can find a way to express it in the usual framework of variables and formulas, maybe we'll come up with other ideas for Core that would make it easier.

But in any case I'd recommend applying YAGNI and narrowing the focus to the specific business problem you want to solve, and afterwards extracting more general insights from it, rather than the other way around.
